<a href="https://colab.research.google.com/github/antonyYG/practica1/blob/main/practicaCalificada1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejercicio 1

In [2]:
import numpy as np


1.1

In [5]:
vector = np.arange(1,21)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


1.2

In [26]:
vector = np.random.rand(9)
print(vector)
vector.reshape(3,3)

[0.90923215 0.15301478 0.26064489 0.54608415 0.12425173 0.83208757
 0.48597967 0.54555289 0.02389439]


array([[0.90923215, 0.15301478, 0.26064489],
       [0.54608415, 0.12425173, 0.83208757],
       [0.48597967, 0.54555289, 0.02389439]])

1.3

In [29]:
vector = np.random.randint(0,10,16)
print(vector.reshape(4,4))
vector.reshape(2,8)

[[5 7 2 1]
 [9 1 4 6]
 [2 2 8 1]
 [3 8 5 1]]


array([[5, 7, 2, 1, 9, 1, 4, 6],
       [2, 2, 8, 1, 3, 8, 5, 1]])

1.4

In [40]:
array= np.random.rand(10)
array

array([0.21700159, 0.81838675, 0.61865056, 0.29604266, 0.41811475,
       0.87151052, 0.09672467, 0.83335662, 0.05623687, 0.28762495])

1.5

In [52]:
vector1 = np.random.randint(0,10,10)
vector2 = np.random.randint(0,10,10)
array = vector1.reshape(2,5)
array2 = vector2.reshape(2,5)
concatenar = np.concatenate((array,array2),axis=0)
print(concatenar)

[[0 2 5 9 7]
 [2 3 4 9 3]
 [0 0 6 1 4]
 [8 2 8 9 2]]


Ejercicio 2

1.1

In [67]:
vector1 = np.random.randint(1,10,9)
vector2 = np.random.randint(1,10,9)
print("Suma", vector1 + vector2)
print("resta", vector1 - vector2)
print("multiplicaciom", vector1 * vector2)
print("Division", vector1 / vector2)

Suma [15 10  9 12 12 15 13 12 14]
resta [-3 -8 -7  6 -4 -3  1  6  2]
multiplicaciom [54  9  8 27 32 54 42 27 48]
Division [0.66666667 0.11111111 0.125      3.         0.5        0.66666667
 1.16666667 3.         1.33333333]


1.2

In [69]:
vector1 = np.random.randint(1,10,9)
print(vector1)
mediana=np.median(vector1)
media=np.mean(vector1)
var=np.std(vector1)
print("mediana",mediana)
print("media",media)
print("varianza",var)

[8 1 2 5 4 1 5 2 9]
mediana 4.0
media 4.111111111111111
varianza 2.7666443551086073


1.3

In [71]:
vector = np.random.randint(1,50,4)
print(vector)
max = np.max(vector)
division = np.divide(vector,max)
print(division)

[29 27 28 25]
[1.         0.93103448 0.96551724 0.86206897]


1.4

In [86]:
vector = np.random.randint(1,20,4)
print(vector)

# Find the index of the maximum value
index_of_max = np.argmin(vector)
print("Index of maximum value:", index_of_max)


[ 8 11 14 17]
Index of maximum value: 0


In [88]:
vector = np.random.randint(1,20,4)
print(vector)

max_value = np.max(vector)
index_of_max = np.argmax(vector)
print("Maximo valor:", max_value)
print("Indice:", index_of_max)

min_value = np.min(vector)
index_of_min = np.argmin(vector)
print("Minimo valor:", min_value)
print("Indice:", index_of_min)

[15  7  5 15]
Maximo valor: 15
Indice: 0
Minimo valor: 5
Indice: 2


1.5

In [101]:
matri1 = np.random.randint(1,10,9)
matri2 = np.random.randint(1,10,9)
matri1 = matri1.reshape(3,3)
matri2 = matri2.reshape(3,3)
print(matri1)
print(matri2)
print("Multiplicacion ")
print( matri1 * matri2)

[[6 6 5]
 [1 7 5]
 [3 8 2]]
[[8 5 5]
 [4 7 8]
 [4 9 1]]
Multiplicacion 
[[48 30 25]
 [ 4 49 40]
 [12 72  2]]


Ejercicio 3

1.1

In [99]:
pares ={}
vector = np.random.randint(1,20,10)
for i in range(len(vector)):
    if vector[i] % 2 == 0:
        pares[i] = int(vector[i])

print(vector)
print(pares)

[10 17 19 13 17 14 15 10 18 17]
{0: 10, 5: 14, 7: 10, 8: 18}


1.2

In [103]:
mayores= {}
vector = np.random.randint(1,20,10)
for i in range(len(vector)):
    if vector[i] > 5:
        mayores[i] = int(vector[i])
print(vector)
print(mayores)

[ 5 14 16  3  4 18  5 13 15  4]
{1: 14, 2: 16, 5: 18, 7: 13, 8: 15}


1.3

In [113]:
iguales_cer={}
vector = np.random.randint(0,20,10)
for i in range(len(vector)):
    if vector[i] == 0:
        iguales_cer[i] = int(vector[i])
print(vector)
print(iguales_cer)

[11 18  5  4  1  0 13  7  9 18]
{5: 0}


1.4

In [114]:
negetivos = {}
vector = np.random.randint(-20,20,10)
for i in range(len(vector)):
    if vector[i] < 0:
        negetivos[i] = int(vector[i])
print(vector)
print(negetivos)

[ 18  14  -8   8  12  -2  10   9 -12  10]
{2: -8, 5: -2, 8: -12}


1.5

In [120]:
mayores_cincuenta = {}

vector = np.random.randint(0,100,10)

for i in range(len(vector)):
    if vector[i] > 50:
        mayores_cincuenta[i] = int(vector[i])

print(vector)
media = np.mean(list(mayores_cincuenta.values()))
print(mayores_cincuenta)
print(media)

[81 12 10  3 26 17 44 78 80 79]
{0: 81, 7: 78, 8: 80, 9: 79}
79.5


Ejercicio 4

1.1

In [121]:
vector = np.random.randint(0,100,10)
print(vector)
for i in range(len(vector)):
    if vector[i] > 5:
       vector[i] = 0
print(vector)

[50 91  2 50 99 28 91  3 32 16]
[0 0 2 0 0 0 0 3 0 0]


1.2

In [132]:
vector1 = np.array([True, False, True, False, True])
vector2 = np.array([False, False, True, True, True])

and_resultado = vector1 & vector2
print("Logical AND result:", and_resultado)

or_resultado = vector1 | vector2
print("Logical OR result:", or_resultado)

Logical AND result: [False False  True False  True]
Logical OR result: [ True False  True  True  True]


1.3

In [123]:
multipolo_tres = 0
vector = np.random.randint(1,9,10)
print(vector)
for i in range(len(vector)):
    if vector[i] % 3 == 0:
        multipolo_tres += 1
print(multipolo_tres)
#

[2 1 2 4 3 1 6 4 7 5]
2


1.4


In [130]:
vector = np.random.randint(0,10,8)
print(vector)
index = np.nonzero(vector)
print(index)

[8 4 6 0 9 9 8 4]
(array([0, 1, 2, 4, 5, 6, 7]),)


1.5


In [145]:
valor = int(input("Ingrese un valor: "))
vector = np.random.randint(0,20,10)
print(vector)
if vector.max() < valor:
    print("El numero ingresado es mayor al vector")
else:
  print("El numero ingresado es menor al vector")
print(vector.max())


Ingrese un valor: 5000
[13  3  2  7  1  8 13 15 14 17]
El numero ingresado es mayor al vector
17


Ejercicio 5

1.1

In [149]:
vector = np.random.randint(1,10,6)
cuadrado = np.square(vector)
print(vector)
print(cuadrado)

[1 6 8 5 6 5]
[ 1 36 64 25 36 25]


1.2

In [151]:
vector = np.random.randint(1,20,8)
exponencial = np.power(vector,3)
print(vector)
print(exponencial)

[ 7  5  8  5  8  9 11  3]
[ 343  125  512  125  512  729 1331   27]


1.3


In [153]:
vector = np.random.randint(1,20,12)
vector.reshape(4,3)

array([[ 9, 15, 17],
       [19,  8, 14],
       [14,  4,  4],
       [ 4,  8,  1]])